name: auto-record

on:
  push:
    branches:
      - dev

jobs:
  auto-record:
    runs-on: ubuntu-latest

    steps:
      - name: setup-python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: clone-google-tests
        run: git clone https://github.com/google/googletest.git third_party/googletest

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: auto-record
        working-directory: auto_record
        run: python record.py

      - name: deploy
        working-directory: auto_record
        run: |
          git checkout -b auto_record
          git add ./records/
          git commit
          git push origin auto_record
