name: visualizer-build

on:
  push:
    branches:
      - dev

jobs:
  osx-build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: |
          cd ./third_party/openFrameworks/scripts/osx/
          sh ./download_libs.sh
          cd ../../../../visualizer
          make build

  linux-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: |
          cd ./third_party/openFrameworks/scripts/linux/
          sh ./download_libs.sh
          cd ../../../../visualizer
          make build
