name: build_visualizer

on:
  push:
    branches:
      - dev

jobs:
  build-osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: |
          cd ./third_party/openFrameworks/scripts/osx/
          sh ./download_libs.sh -v 0.11.0
          cd ../../../../visualizer
          make build
