name: public

on:
  push:
    branches:
      - public

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: add zip file
        run: |
          python docs/generator.py
          zip -r docs/code.zip ./ -x *.git*

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
