name: public

on:
  push:
    branches:
      - public

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: add zip file
        run: |
          mkdir deploy
          zip -r deploy/code.zip ./
          cp -r docs/ deploy

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
