name: test

on:
  push:
    branches:
      - dev

jobs:
  dev-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: test
        working-directory: build
        run: ./test

      - name: run-app
        working-directory: build
        run: ./app -i ../instances/sample.txt -s PIBT -o result.txt -v

      - name: visualizer-build
        working-directory: visualizer
        run: make build
